#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("EvolveMaterialDesign.Resource", IsApplication=true)]

namespace EvolveMaterialDesign
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int paper_state_list_anim_material = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int accent = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_shadow_start_color = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int deep_purple_A200 = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int main_green = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int main_red = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int material_blue_500 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int material_blue_700 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int primary = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int primary_dark = 2131034120;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_compat_inset_shadow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_default_elevation = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_default_radius = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bread_cat = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_add_minus_anim = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_add_remove_000 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_add_remove_001 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_add_remove_002 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_add_remove_003 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_add_remove_004 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_add_remove_005 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_add_remove_006 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_mtrl_alpha = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_variant1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_variant2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_variant3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_variant4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_variant5 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int chris = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int james = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int jeremie = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int monkey1 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int monkey2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int monkey3 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int monkey_mask = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int monkey_ripple = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int spaced_list_divider = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tortilla_cat = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001e
			public const int addState = 2131296286;
			
			// aapt resource value: 0x7f090018
			public const int avatarView1 = 2131296280;
			
			// aapt resource value: 0x7f09001a
			public const int avatarView2 = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int avatarView3 = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int avatarView4 = 2131296284;
			
			// aapt resource value: 0x7f090012
			public const int button1 = 2131296274;
			
			// aapt resource value: 0x7f090017
			public const int button2 = 2131296279;
			
			// aapt resource value: 0x7f090002
			public const int checkBox1 = 2131296258;
			
			// aapt resource value: 0x7f090008
			public const int checkBox2 = 2131296264;
			
			// aapt resource value: 0x7f09000d
			public const int drawableAnimBtn = 2131296269;
			
			// aapt resource value: 0x7f090000
			public const int frameLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int frameLayout2 = 2131296263;
			
			// aapt resource value: 0x7f090014
			public const int imageButton1 = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int imageButton2 = 2131296277;
			
			// aapt resource value: 0x7f09000c
			public const int inkBtn = 2131296268;
			
			// aapt resource value: 0x7f090019
			public const int item_text_primary = 2131296281;
			
			// aapt resource value: 0x7f090009
			public const int layoutBtn = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout1 = 2131296257;
			
			// aapt resource value: 0x7f090011
			public const int panel1 = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int panel2 = 2131296275;
			
			// aapt resource value: 0x7f090016
			public const int panel3 = 2131296278;
			
			// aapt resource value: 0x7f09000e
			public const int paperContainer = 2131296270;
			
			// aapt resource value: 0x7f09000a
			public const int paperCraftBtn = 2131296266;
			
			// aapt resource value: 0x7f090004
			public const int radioButton1 = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int radioButton2 = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int radioButton3 = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int radioGroup1 = 2131296259;
			
			// aapt resource value: 0x7f09001d
			public const int removeState = 2131296285;
			
			// aapt resource value: 0x7f09000b
			public const int rippleBtn = 2131296267;
			
			// aapt resource value: 0x7f09000f
			public const int view1 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int view2 = 2131296272;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AnimatedDrawableLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int InkResponseLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PaperCraftLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RippleFeedbackLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SpacedLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int CardView_Dark = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Light = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int EvolveMaterialTheme = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
