#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidLSamples.Resource", IsApplication=true)]

namespace AndroidLSamples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int paper_state_list_anim_material = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int notification_priority = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int ratio = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050012
			public const int accent = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_shadow_start_color = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int color_1 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int color_2 = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int deep_purple_A200 = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int main_green = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int main_red = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int material_blue_500 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int material_blue_700 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int primary = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int primary_dark = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int xam_blue = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int xam_dark_blue = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int xam_gray = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int xam_green = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int xam_light_gray = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int xam_medium_blue = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int xam_purple = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int activity_margin = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int cardview_compat_inset_shadow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_default_elevation = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_default_radius = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int grid_spacing = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bass1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bass2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bass3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bass4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bass5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bass6 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bass7 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bassnectar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_mtrl_alpha = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_variant1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_variant2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_variant3 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_variant4 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int caterpiller = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int evolve = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int flying_in_the_light_large = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int gear = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_notification = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int jelly_fish_2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int lone_pine_sunset = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int look_me_in_the_eye = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int monkey = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int mycircle = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int over_there = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int rainbow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int rect_blue = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int rect_orange = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int rect_red = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int sample1 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int sample2 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int shape = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int shape2 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int xamarin = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int xamarin_white = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b002c
			public const int action_edit = 2131427372;
			
			// aapt resource value: 0x7f0b002d
			public const int action_save = 2131427373;
			
			// aapt resource value: 0x7f0b002b
			public const int action_save2 = 2131427371;
			
			// aapt resource value: 0x7f0b0012
			public const int add = 2131427346;
			
			// aapt resource value: 0x7f0b0014
			public const int animate = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int animate_bottom = 2131427349;
			
			// aapt resource value: 0x7f0b0007
			public const int apply_palette = 2131427335;
			
			// aapt resource value: 0x7f0b0017
			public const int button1 = 2131427351;
			
			// aapt resource value: 0x7f0b0016
			public const int checkBox1 = 2131427350;
			
			// aapt resource value: 0x7f0b0009
			public const int colors = 2131427337;
			
			// aapt resource value: 0x7f0b0026
			public const int drawableAnimBtn = 2131427366;
			
			// aapt resource value: 0x7f0b001c
			public const int editText1 = 2131427356;
			
			// aapt resource value: 0x7f0b0027
			public const int explode = 2131427367;
			
			// aapt resource value: 0x7f0b000c
			public const int extended = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int extended_photo = 2131427341;
			
			// aapt resource value: 0x7f0b0000
			public const int grid = 2131427328;
			
			// aapt resource value: 0x7f0b0010
			public const int high_priority = 2131427344;
			
			// aapt resource value: 0x7f0b0008
			public const int horizontalScrollView = 2131427336;
			
			// aapt resource value: 0x7f0b0001
			public const int image = 2131427329;
			
			// aapt resource value: 0x7f0b0020
			public const int imageView = 2131427360;
			
			// aapt resource value: 0x7f0b0029
			public const int imageview_item = 2131427369;
			
			// aapt resource value: 0x7f0b0025
			public const int inkBtn = 2131427365;
			
			// aapt resource value: 0x7f0b0023
			public const int layoutBtn = 2131427363;
			
			// aapt resource value: 0x7f0b0006
			public const int main_layout = 2131427334;
			
			// aapt resource value: 0x7f0b0028
			public const int move = 2131427368;
			
			// aapt resource value: 0x7f0b0013
			public const int my_view = 2131427347;
			
			// aapt resource value: 0x7f0b0002
			public const int name = 2131427330;
			
			// aapt resource value: 0x7f0b0019
			public const int radioButton1 = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int radioButton2 = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int radioButton3 = 2131427355;
			
			// aapt resource value: 0x7f0b0018
			public const int radioGroup1 = 2131427352;
			
			// aapt resource value: 0x7f0b0011
			public const int recycler_view = 2131427345;
			
			// aapt resource value: 0x7f0b0024
			public const int rippleBtn = 2131427364;
			
			// aapt resource value: 0x7f0b001f
			public const int seekBar1 = 2131427359;
			
			// aapt resource value: 0x7f0b000a
			public const int simple = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int simple_photo = 2131427339;
			
			// aapt resource value: 0x7f0b000f
			public const int spinner_visibility = 2131427343;
			
			// aapt resource value: 0x7f0b001d
			public const int switch1 = 2131427357;
			
			// aapt resource value: 0x7f0b0021
			public const int textView = 2131427361;
			
			// aapt resource value: 0x7f0b000e
			public const int textView1 = 2131427342;
			
			// aapt resource value: 0x7f0b0022
			public const int textView2 = 2131427362;
			
			// aapt resource value: 0x7f0b002a
			public const int textview_name = 2131427370;
			
			// aapt resource value: 0x7f0b001e
			public const int toggleButton1 = 2131427358;
			
			// aapt resource value: 0x7f0b0003
			public const int view1 = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int view3 = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int view4 = 2131427333;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_animations_1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_animations_2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_card = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_image_detail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_image_list = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_notifications = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_recycler_view = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_recycler_view_add_remove = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_reveal = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_themes = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int grid_item = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int item = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int palette_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int recycleritem_card = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int menu1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int menu2 = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int hello = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070006
			public const int AppThemeLight = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int AppThemeLightNoDrop = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int CardView_Dark = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Light = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int CardView_XamBlue = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int CardView_XamGreen = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int CardView_XamPurple = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int EvolveMaterialTheme = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int MaterialDark = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int MaterialLight = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int TransparentTheme = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int TransparentTheme_ActionBar = 2131165196;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			public static int[] HeightAdjustableImageView = new int[]
			{
					2130771979};
			
			// aapt resource value: 0
			public const int HeightAdjustableImageView_ratio = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
